# Generated by Django 4.0.4 on 2022-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
